#include <iostream>

using namespace std;

int main()
{
    string input= "0";
    cout << "Character? ";
    cin >> input;
    string tri= input;

    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
    cout << tri << endl;
    tri= tri+ input;
}
