#include <iostream>

using namespace std;

int main()
{
    string tri= "*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";
    cout << tri << endl;
    tri= tri+"*";

    return 0;
}
