#include <iostream>

using namespace std;

int main()
{
    int count = 0;
    cout << "0 " ;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    cout << (count%7)+1 << " ";
    count = count + 1;
    return 0;
}
