#include <iostream>

using namespace std;

int main()
{
    int count = 0;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    cout << count << " ";
    count = count + 1;
    return 0;
}
